apiVersion: v1
data:
  AI_SYMPTOM_SERVICE_URL: http://ai-symptom-service:5006
  AI_SYMPTOM_SERVICE_URL: http://ai-symptom-service:5006
  AUTH_PORT: "5001"
  AUTH_SERVICE_URL: http://auth-service:5001
  DEFAULT_ROLE: user
  DOCTOR_PORT: "5007"
  DOCTOR_SERVICE_URL: http://doctor-service:5007
  GATEWAY_PORT: "5000"
  JWT_EXPIRATION: 30d
  PRESCRIPTION_PORT: "5004"
  PRESCRIPTION_SERVICE_URL: http://prescription-service:5004
  SYMP_PORT: "5006"
  SUPPORTED_ROLES: user,admin,doctor
  TELEMEDICINE_PORT: "5003"
  TELEMEDICINE_SERVICE_URL: http://telemedicine-service:5003
  USER_PORT: "5002"
  USER_SERVICE_URL: http://user-service:5002

kind: ConfigMap
metadata:
  name: smart-healthcare-config
