apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: smart-healthcare/payment-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5009
          envFrom:
            - configMapRef:
                name: smart-healthcare-config
            - secretRef:
                name: smart-healthcare-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  ports:
    - port: 5009
      targetPort: 5009
  selector:
    app: payment-service