apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: smart-healthcare/user-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
        envFrom:
        - configMapRef:
            name: smart-healthcare-config
        - secretRef:
            name: smart-healthcare-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
  - port: 5002
    targetPort: 5002
  selector:
    app: user-service
