const OpenAI = require("openai");

/**
 * Get configured DeepSeek client
 */
function getDeepSeekClient() {
  const apiKey = process.env.DEEPSEEK_API_KEY;

  if (!apiKey) {
    throw new Error("DEEPSEEK_API_KEY is missing in environment variables");
  }

  return new OpenAI({
    apiKey: apiKey,
    baseURL: "https://api.deepseek.com",
  });
}

/**
 * Refine messy OCR text using DeepSeek AI
 * @param {string} rawText - The raw (noisy) text from Tesseract
 * @returns {Promise<string>} - The refined and styled text
 */
async function refinePrescriptionText(rawText) {
  const openai = getDeepSeekClient();

  const prompt = `
    You are a professional medical assistant. I will provide you with a raw text extract from a medical prescription (generated by an OCR tool which might be noisy and contains errors).
    
    Your task is to:
    1. Clean up the text: Fix typos, remove noise (random characters), and identify medical terms.
    2. Structure it professionally: Identify the hospital name, patient details, medications, and dosages.
    3. DISAMBIGUATE: If a medication name is misspelled, use your medical knowledge to correct it (e.g., "Incontrol Acid" might be "Lansoprazole" or similar, "Bh bo hep" might be something else).
    
    Format the output as HIGHLY STYLED MARKDOWN as follows:
    
    # 🏥 Prescription Analysis (AI Refined)
    
    ## 🏥 Hospital Information
    - **Hospital Name:** [Corrected hospital name]
    - **Contact:** [Address/Phone/Email if found]
    
    ## 👤 Patient Details
    - **Name:** [Patient Name]
    - **Age/Gender:** [Age/Gender]
    - **Date:** [Prescription Date]
    
    ---
    
    ## 💊 Medications
    [List each medication clearly]
    - **[Medication Name]**: [Dosage/Frequency/Duration]
    
    ---
    
    ## 📝 Additional Notes / Instructions
    - [Handwritten notes or symptoms identified]
    
    ---
    *Disclaimer: This is an AI-assisted analysis of a handwritten document. Please verify with a pharmacist.*
    
    RAW TEXT TO ANALYZE:
    "${rawText}"
  `;

  const response = await openai.chat.completions.create({
    model: "deepseek-chat",
    messages: [
      { role: "system", content: "You are an expert medical transcriptionist." },
      { role: "user", content: prompt },
    ],
    temperature: 0.3, // Lower temperature for accuracy
  });

  return response.choices[0].message.content;
}

module.exports = { refinePrescriptionText };
