name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 20.198.240.101
          username: azureuser
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/smart-healthcare-system
            git pull origin main
            docker compose down
            docker compose up -d --build